# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'final-project-shalini' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for final-project-shalini

  target 'final-project-shaliniTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'final-project-shaliniUITests' do
    # Pods for testing
  end

end
