# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'final-project-shalini' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for final-project-shalini
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


  target 'final-project-shaliniTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'final-project-shaliniUITests' do
    # Pods for testing
  end

end
